import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import sys, os, json
import datetime
import base64
import hmac
import time

try:
    from streamlit_cookies_manager import EncryptedCookieManager
except Exception:  # optional dependency
    EncryptedCookieManager = None

# ---- Fibonacci Overlay Chart ----
import matplotlib.pyplot as plt

def fib_overlay_chart(dates, values, title="P85 Cycle Time with Fibonacci Bands"):
    import numpy as np
    import matplotlib.pyplot as plt
    import matplotlib.dates as mdates

    values = np.array(values, dtype=float)

    low = np.nanmin(values)
    high = np.nanmax(values)

    fib = np.array([1.0, 0.786, 0.618, 0.5, 0.382, 0.236, 0.0])
    fib_vals = low + (high - low) * fib

    fig, ax = plt.subplots(figsize=(14, 4))

    ax.axhspan(fib_vals[2], fib_vals[0], color="#ffebee", alpha=1.0, edgecolor="#e57373", linewidth=0.5)
    ax.axhspan(fib_vals[4], fib_vals[2], color="#fff3cd", alpha=1.0, edgecolor="#ffb74d", linewidth=0.5)
    ax.axhspan(fib_vals[-1], fib_vals[4], color="#c8e6c9", alpha=1.0, edgecolor="#81c784", linewidth=0.5)

    for lvl in fib_vals:
        ax.axhline(lvl, linestyle="--", linewidth=0.6, color="gray", alpha=0.7)

    ax.plot(dates, values, marker="o", linewidth=2.2, color="#42a5f5", label="P85")

    x = mdates.date2num(dates)
    mask = ~np.isnan(values)
    if mask.sum() > 1:
        coef = np.polyfit(x[mask], values[mask], 1)
        trend = np.poly1d(coef)
        ax.plot(dates, trend(x), color="#e53935", linewidth=2.8, linestyle="-", label="Trend")

    ax.set_title(title)
    ax.set_ylabel("P85 CT (days)")
    ax.legend(loc="upper left")

    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
    fig.autofmt_xdate()

    plt.tight_layout()
    return fig


# Ensure local imports work
sys.path.append(os.path.dirname(__file__))

from timepiece_integration import (
    fetch_status_durations,
    fetch_transition_dates,
    parse_status_rules,
    build_dataframe,
)

st.set_page_config(page_title="CTapp — Flow Analytics", layout="wide")

# ---- UI polish ----
def _inject_css(path: str = "ui.css"):
    """Load CSS reliably on case-sensitive filesystems (Streamlit Cloud runs on Linux)."""
    try:
        css_path = path
        if not os.path.isabs(css_path):
            css_path = os.path.join(os.path.dirname(__file__), css_path)
        with open(css_path, "r", encoding="utf-8") as f:
            st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
    except Exception as e:
        # In production we keep quiet; on Setup page we surface a warning.
        st.session_state["_css_load_error"] = str(e)

_inject_css()

# ---- Local config ----
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "config.json")


def load_config() -> dict:
    try:
        if os.path.exists(CONFIG_PATH):
            with open(CONFIG_PATH, "r", encoding="utf-8") as f:
                return json.load(f) or {}
    except Exception:
        return {}
    return {}


def save_config(cfg: dict) -> None:
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2, sort_keys=True)


def save_api_key_to_secrets(api_key: str) -> None:
    api_key = (api_key or "").strip()
    secrets_dir = os.path.join(os.path.dirname(__file__), ".streamlit")
    os.makedirs(secrets_dir, exist_ok=True)
    secrets_path = os.path.join(secrets_dir, "secrets.toml")
    content = (
        "# Auto-generated by CTapp\n"
        "# Keep this file private. It contains your Timepiece API key.\n\n"
        f"TIMEPIECE_API_KEY = \"{api_key}\"\n"
    )
    with open(secrets_path, "w", encoding="utf-8") as f:
        f.write(content)


CFG = load_config()

# Keep commonly edited config values in session_state so Setup can edit them
# and the rest of the app can use them without cluttering the sidebar.
DEFAULT_RULES = """Blocked = On Hold (C7SM)
Development = In Development (C7SM), In Progress (C7O), In Development (C7T4)
Review = Review (C7SM)"""

st.session_state.setdefault("cfg_filter_id", str(CFG.get("filter_id", "10580")))
st.session_state.setdefault("cfg_rules_text", str(CFG.get("rules_text", DEFAULT_RULES)))


# ---- Simple shared login gate (optional) ----
# Set APP_USERNAME + APP_PASSWORD in Streamlit secrets to enable.

def _auth_enabled() -> bool:
    try:
        u = str(st.secrets.get("APP_USERNAME", "") or "").strip()
        p = str(st.secrets.get("APP_PASSWORD", "") or "").strip()
        return bool(u and p)
    except Exception:
        return False


def _auth_secret() -> str:
    try:
        return str(st.secrets.get("APP_AUTH_SECRET", "") or "").strip()
    except Exception:
        return ""


_COOKIE_MGR = None


def _cookies():
    """Return a singleton cookie manager if available, else None.

    streamlit-cookies-manager uses a fixed component key internally.
    We must ensure we instantiate the component at most once per script run.
    A module-level singleton achieves that without Streamlit element key clashes.
    """
    global _COOKIE_MGR
    if EncryptedCookieManager is None:
        return None
    secret = _auth_secret()
    if not secret:
        return None

    if _COOKIE_MGR is None:
        _COOKIE_MGR = EncryptedCookieManager(prefix="ctapp_", password=secret)

    return _COOKIE_MGR


def _set_auth_cookie() -> None:
    cm = _cookies()
    if cm is None:
        return
    try:
        if not cm.ready():
            return
    except Exception:
        return
    cm["authed"] = "1"
    cm.save()


def _clear_auth_cookie() -> None:
    cm = _cookies()
    if cm is None:
        return
    try:
        if not cm.ready():
            return
    except Exception:
        return
    try:
        del cm["authed"]
    except Exception:
        cm["authed"] = ""
    cm.save()


def _has_auth_cookie() -> bool:
    cm = _cookies()
    if cm is None:
        return False
    try:
        if not cm.ready():
            return False
    except Exception:
        return False
    return str(cm.get("authed", "")) == "1"


def _check_login() -> None:
    if not _auth_enabled():
        return

    cookie_persistence_available = False
    if _auth_secret() and EncryptedCookieManager is not None:
        cm = _cookies()
        try:
            if cm is not None and not cm.ready():
                st.info("Preparing secure session…")
                st.stop()
            cookie_persistence_available = bool(cm is not None and cm.ready())
        except Exception:
            cookie_persistence_available = False

    # If already authed in-session but cookie is now available, persist it.
    if st.session_state.get("_authed") is True and cookie_persistence_available and not _has_auth_cookie():
        _set_auth_cookie()

    # Auto-auth via cookie (survives refresh)
    if _has_auth_cookie():
        st.session_state["_authed"] = True
        return

    if st.session_state.get("_authed") is True:
        return

    st.markdown("## Sign in")
    st.caption("Internal access — enter the shared credentials.")

    # (debug removed)

    u_in = st.text_input("Username", key="login_user")
    p_in = st.text_input("Password", type="password", key="login_pass")

    col1, col2 = st.columns([1, 2])
    do = col1.button("Sign in", type="primary", use_container_width=True)
    if _auth_secret():
        col2.caption("This device will stay signed in.")
    else:
        col2.caption("Set APP_AUTH_SECRET in secrets to persist login across refresh.")

    if do:
        try:
            u = str(st.secrets.get("APP_USERNAME", "") or "").strip()
            p = str(st.secrets.get("APP_PASSWORD", "") or "").strip()
        except Exception:
            u, p = "", ""

        if hmac.compare_digest(u_in.strip(), u) and hmac.compare_digest(p_in, p):
            st.session_state["_authed"] = True
            if cookie_persistence_available:
                _set_auth_cookie()
                st.success("Signed in. (will persist on this device)")
            else:
                st.success("Signed in.")
                st.caption("Note: persistence will activate once the secure session is ready. If you refresh and get logged out, sign in once more.")
            st.rerun()
        else:
            st.error("Invalid username or password.")

    st.stop()


_check_login()


def assign_team_from_prefix(issue_key: str, prefix_cfg: dict) -> str:
    issue_key = str(issue_key or "")
    for pref, meta in (prefix_cfg or {}).items():
        if pref and issue_key.startswith(pref):
            return str(meta.get("team_name") or pref)
    # Back-compat defaults
    if issue_key.startswith("C7SM"):
        return "Team 1"
    if issue_key.startswith("C7O"):
        return "Team 2"
    if issue_key.startswith("C7T4"):
        return "Team 4"
    return "Other"


def http_error_text(e: Exception) -> str:
    msg = str(e)
    try:
        import requests

        if isinstance(e, requests.HTTPError) and getattr(e, "response", None) is not None:
            msg = f"{e.response.status_code} {e.response.reason}: {e.response.text}"
    except Exception:
        pass
    return msg


# ---- UI helpers ----
def card_start(title: str, hero: bool = False, badge: str | None = None):
    """Legacy wrapper (works visually but cannot reliably wrap Streamlit elements)."""
    klass = "card card-hero" if hero else "card"
    badge_html = f"<span class='badge'>{badge}</span>" if badge else ""
    st.markdown(
        f"<div class='{klass}'><div class='card-title'><span>{title}</span>{badge_html}</div>",
        unsafe_allow_html=True,
    )


def card_end():
    st.markdown("</div>", unsafe_allow_html=True)


def kpi_card(title: str, value: str, caption: str | None = None, badge: str | None = None, hero: bool = False):
    """Render a KPI card as a single HTML block so header+value are in the same container."""
    klass = "card card-hero" if hero else "card"
    badge_html = f"<span class='badge'>{badge}</span>" if badge else ""
    cap_html = f"<div class='kpi-caption'>{caption}</div>" if caption else ""
    st.markdown(
        f"""
<div class='{klass}'>
  <div class='card-title'><span>{title}</span>{badge_html}</div>
  <div class='kpi-value'>{value}</div>
  {cap_html}
</div>
""",
        unsafe_allow_html=True,
    )


def kpi_card_md(title: str, value: str, badge: str | None = None):
    klass = "card"
    badge_html = f"<span class='badge'>{badge}</span>" if badge else ""
    st.markdown(
        f"""
<div class='{klass}'>
  <div class='card-title'><span>{title}</span>{badge_html}</div>
  <div class='kpi-value-md'>{value}</div>
</div>
""",
        unsafe_allow_html=True,
    )


# ===================== SIDEBAR =====================
SECTIONS = [
    "Team Dashboard",
    "Events",
    "Report Pack",
    "Setup",
    "Diagnostics",
]

TEAM_TABS = [
    "Overview",
    "Reliability",
    "Risks",
    "Bottlenecks",
    "Forecasting",
    "Slowest Items",
    "Sprints",
]

with st.sidebar:
    st.title("CTapp")
    st.caption("OBSS Timepiece Cloud → cycle time, predictability, risk")

    # API key
    api_key = None
    try:
        api_key = st.secrets.get("TIMEPIECE_API_KEY", None)
    except Exception:
        api_key = None

    if not api_key:
        api_key = st.text_input(
            "Timepiece API Key",
            value="",
            type="password",
            help="You can save this locally (writes .streamlit/secrets.toml) so you don't need to paste it each run.",
        )
        colk1, colk2 = st.columns([1, 1])
        if colk1.button("Save API key locally", use_container_width=True):
            if not api_key.strip():
                st.error("Paste an API key first.")
            else:
                save_api_key_to_secrets(api_key)
                st.success("Saved. Refresh to load from secrets.")
        colk2.caption("Writes .streamlit/secrets.toml")
    else:
        st.caption("API Key loaded from secrets.")

    # Sidebar intentionally kept minimal.
    st.caption(f"Filter: {st.session_state.get('cfg_filter_id','—')}")

    fetch_button = st.button("Fetch Data", type="primary", use_container_width=True)

    st.markdown("---")
    section_icons = {
        "Team Dashboard": "◼",
        "Events": "✦",
        "Report Pack": "▤",
        "Setup": "⚙",
        "Diagnostics": "⌁",
    }

    st.markdown("<div class='sidebar-nav'>", unsafe_allow_html=True)
    section = st.radio(
        "",
        SECTIONS,
        index=0,
        key="nav_section",
        format_func=lambda s: f"{section_icons.get(s,'•')}  {s}",
    )
    st.markdown("</div>", unsafe_allow_html=True)

    # Team tab navigation is rendered in the main content as pill tabs (fintech style)
    page = section


api_key = (api_key or "").strip()
filter_id = str(st.session_state.get("cfg_filter_id", "")).strip()
rules_text = str(st.session_state.get("cfg_rules_text", "")).strip()

# Setup should be accessible even before credentials/data are configured.
if page != "Setup":
    if not api_key or not filter_id:
        st.info("Enter API Key + Filter ID, then press Fetch Data.")
        st.stop()


# ===================== FETCH DATA =====================
# Allow fetch from top bar too
fetch_trigger = bool(fetch_button) or bool(st.session_state.pop("do_fetch", False))
if fetch_trigger:
    with st.spinner("Fetching reports from Timepiece..."):
        try:
            duration_data = fetch_status_durations(api_key, filter_id)
            transition_data = fetch_transition_dates(api_key, filter_id)
            status_rules = parse_status_rules(rules_text)
            prefix_status_ids = CFG.get("prefix_status_ids", None)
            raw = build_dataframe(duration_data, transition_data, status_rules, prefix_status_ids=prefix_status_ids)

            # Team assignment from prefix config
            prefix_cfg = CFG.get("prefix_status_ids", {})
            if not raw.empty and "Key" in raw.columns:
                raw["Team"] = raw["Key"].apply(lambda k: assign_team_from_prefix(k, prefix_cfg))
            else:
                raw["Team"] = "Unknown"

            raw["_bucketer"] = pd.to_datetime(raw.get("End"), errors="coerce")

            st.session_state["raw_data"] = raw
            st.session_state["last_refreshed"] = datetime.datetime.now().isoformat(timespec="seconds")

            # Detect prefixes
            if "Key" in raw.columns:
                prefs = (
                    raw["Key"].astype(str).str.split("-", n=1).str[0]
                    .replace({"": None, "nan": None})
                    .dropna()
                    .unique()
                    .tolist()
                )
                prefs = sorted([p.strip() for p in prefs if p and p.strip()], key=lambda x: x.lower())
                st.session_state["_detected_prefixes"] = prefs

            # Cache status options for dropdowns
            header_cols = duration_data.get("table", {}).get("header", {}).get("valueColumns", [])
            opts = []
            for c in header_cols:
                sid = str(c.get("id", "")).strip()
                name = str(c.get("value", "")).strip()
                if sid and name:
                    opts.append((name, sid))
            opts = sorted(list({(n, i) for (n, i) in opts}), key=lambda x: x[0].lower())
            st.session_state["_status_options"] = opts

        except Exception as e:
            st.error(f"Failed to fetch from Timepiece: {http_error_text(e)}")
            st.stop()


raw = st.session_state.get("raw_data")
has_data = raw is not None and isinstance(raw, pd.DataFrame) and not raw.empty

# Only non-Setup pages require data.
if page != "Setup":
    if not has_data:
        st.info("Fetch data first.")
        st.stop()

# ===================== HEADER =====================
st.title("CTapp — Cycle Time Analysis")

def _team_topbar(raw_df: pd.DataFrame) -> tuple[str, pd.DataFrame, str, str]:
    """Render fintech-style top bar for team context pages."""
    prefixes = sorted(raw_df["Team"].dropna().unique().tolist()) if (raw_df is not None and not raw_df.empty and "Team" in raw_df.columns) else []

    # persisted UI state
    if "ui_team" not in st.session_state:
        st.session_state["ui_team"] = "All Teams"
    if "ui_metric" not in st.session_state:
        st.session_state["ui_metric"] = "P85"
    if "ui_window" not in st.session_state:
        st.session_state["ui_window"] = "30d"

    st.markdown("<div class='topbar'>", unsafe_allow_html=True)
    c1, c2, c3, c4, c5 = st.columns([1.5, 1.0, 1.0, 1.2, 1.3])

    with c1:
        team = st.selectbox(
            "Team",
            ["All Teams"] + prefixes,
            index=0 if st.session_state["ui_team"] == "All Teams" else max(0, (["All Teams"] + prefixes).index(st.session_state["ui_team"]) if st.session_state["ui_team"] in (["All Teams"] + prefixes) else 0),
            key="ui_team",
            label_visibility="collapsed",
        )
        st.caption("Team")

    with c2:
        metric = st.selectbox(
            "Metric",
            ["P85", "Median", "Average"],
            index=["P85", "Median", "Average"].index(st.session_state["ui_metric"]) if st.session_state["ui_metric"] in ["P85", "Median", "Average"] else 0,
            key="ui_metric",
            label_visibility="collapsed",
        )
        st.caption("Metric")

    with c3:
        window = st.selectbox(
            "Window",
            ["30d", "90d", "180d"],
            index=["30d", "90d", "180d"].index(st.session_state["ui_window"]) if st.session_state["ui_window"] in ["30d", "90d", "180d"] else 0,
            key="ui_window",
            label_visibility="collapsed",
        )
        st.caption("Window")

    with c4:
        last_refreshed = st.session_state.get("last_refreshed")
        st.markdown(f"<div class='statusbox'><span class='statusbox-value'>{last_refreshed or '—'}</span></div>", unsafe_allow_html=True)
        st.markdown("<div class='statusbox-label'>Last refresh</div>", unsafe_allow_html=True)

    with c5:
        if st.button("Refresh data", type="primary", use_container_width=True):
            st.session_state["do_fetch"] = True
            st.rerun()

    st.markdown("</div>", unsafe_allow_html=True)

    if team == "All Teams":
        view = raw_df.copy()
    else:
        view = raw_df[raw_df["Team"] == team].copy()

    return team, view, metric, window


# Team selector is irrelevant on Setup; show top bar only for Team Dashboard pages.
if page not in ("Setup", "Events", "Report Pack", "Diagnostics") and has_data:
    selected_team, view_df, ui_metric, ui_window = _team_topbar(raw)
    st.caption("Cycle Time = sum of your configured status buckets (e.g. Blocked + Development + Review)")
else:
    selected_team = "All Teams"
    view_df = raw.copy() if has_data else pd.DataFrame()
    ui_metric = "P85"
    ui_window = "30d"


# ===================== TEAM DASHBOARD (tabs) =====================
if page == "Team Dashboard":
    st.markdown("<div class='pillbar'>", unsafe_allow_html=True)

    # Minimal monochrome glyphs (work without icon fonts)
    tab_icons = {
        "Overview": "◼",
        "Reliability": "✓",
        "Risks": "!",
        "Bottlenecks": "⧖",
        "Forecasting": "↗",
        "Slowest Items": "⇑",
        "Sprints": "⟲",
    }
    fmt = lambda t: f"{tab_icons.get(t, '•')}  {t}"

    try:
        team_tab = st.radio("", TEAM_TABS, index=0, horizontal=True, key="team_tabs_main", format_func=fmt)
    except TypeError:
        team_tab = st.radio("", TEAM_TABS, index=0, key="team_tabs_main", format_func=fmt)

    st.markdown("</div>", unsafe_allow_html=True)
    page = f"Team::{team_tab}"


# ===================== PAGES =====================
if page == "Team::Overview":
    # --- Fintech dashboard layout ---
    # Use the top bar selections as defaults.
    mode = st.selectbox("View", ["Monthly", "Rolling (30d)", "Rolling (14d)"], index=0, key="ov_view")

    metric = {"P85": "P85", "Median": "Median (P50)", "Average": "Average (Mean)"}.get(ui_metric, "P85")
    window_days = {"30d": 30, "90d": 90, "180d": 180}.get(ui_window, 30)

    # Completed items for window calcs
    completed = pd.DataFrame()
    if "End" in view_df.columns and "CT" in view_df.columns:
        completed = view_df.copy()
        completed["End"] = pd.to_datetime(completed["End"], utc=True, errors="coerce")
        completed = completed.dropna(subset=["End", "CT"])

    # Window slice (by completion date)
    end_max = completed["End"].max() if not completed.empty else None
    w = pd.DataFrame()
    if end_max is not None:
        start_w = end_max - pd.Timedelta(days=window_days)
        w = completed[(completed["End"] >= start_w) & (completed["End"] <= end_max)].copy()

    def _metric_val(series: pd.Series) -> float | None:
        if series is None or series.dropna().empty:
            return None
        s = series.astype(float).dropna()
        if metric == "Median (P50)":
            return float(s.median())
        if metric == "Average (Mean)":
            return float(s.mean())
        return float(s.quantile(0.85))

    # KPI row (cards)
    k1, k2, k3, k4 = st.columns(4)

    v = _metric_val(w.get("CT"))
    ct_text = "—" if v is None else f"{v:.1f}"

    with k1:
        kpi_card(f"CT ({window_days}d)", ct_text, caption="days", badge=ui_metric, hero=True)

    with k2:
        kpi_card(f"Throughput ({window_days}d)", str(len(w) if w is not None else 0), caption="Completed items")

    # Reliability (SLE) KPI
    with k3:
        rel = None
        try:
            if not w.empty and "IssueType" in w.columns:
                default_sle = {"Story": 10, "Bug": 5, "Task": 8, "Spike": 12}
                sle_map = dict(default_sle)
                sle_map.update(CFG.get("sle_days_by_type", {}) or {})
                tmp = w[["CT", "IssueType"]].dropna().copy()
                tmp["SLE_days"] = tmp["IssueType"].astype(str).map(sle_map)
                tmp = tmp.dropna(subset=["SLE_days"])
                if not tmp.empty:
                    rel = float((tmp["CT"].astype(float) <= tmp["SLE_days"].astype(float)).mean())
        except Exception:
            rel = None
        rel_text = "—" if rel is None else f"{rel*100:.0f}%"
        kpi_card(f"Reliability ({window_days}d)", rel_text, caption="Target 85%", badge="SLE")

    # WIP at-risk KPI
    with k4:
        risky = 0
        try:
            if "Start" in view_df.columns:
                wd = view_df.copy()
                wd["Start"] = pd.to_datetime(wd["Start"], utc=True, errors="coerce")
                wd["End"] = pd.to_datetime(wd["End"], utc=True, errors="coerce") if "End" in wd.columns else pd.NaT
                wip = wd[wd["Start"].notna() & wd["End"].isna()].copy()
                if not wip.empty:
                    now = pd.Timestamp.now(tz="UTC")
                    wip["Age_days"] = (now - wip["Start"]).dt.total_seconds() / 86400.0
                    default_sle = {"Story": 10, "Bug": 5, "Task": 8, "Spike": 12}
                    sle_map = dict(default_sle)
                    sle_map.update(CFG.get("sle_days_by_type", {}) or {})
                    wip["SLE_days"] = wip.get("IssueType").astype(str).map(sle_map)
                    risky = int(((wip["SLE_days"].notna()) & (wip["Age_days"] >= 0.8 * wip["SLE_days"])).sum())
        except Exception:
            risky = 0
        kpi_card("WIP risk", str(risky), caption="At risk / breached", badge="Now")

    st.markdown("<div style='height:10px'></div>", unsafe_allow_html=True)

    # Issue type tiles for the window
    if "IssueType" in w.columns and not w.empty:
        tcols = st.columns(4)
        agg = None
        if metric == "Median (P50)":
            agg = w.groupby("IssueType")["CT"].median()
        elif metric == "Average (Mean)":
            agg = w.groupby("IssueType")["CT"].mean()
        else:
            agg = w.groupby("IssueType")["CT"].quantile(0.85)
        for i, it in enumerate(["Story", "Bug", "Task", "Spike"]):
            with tcols[i]:
                v = float(agg.get(it)) if it in agg.index else None
                txt = "—" if v is None or pd.isna(v) else f"{v:.1f}"
                kpi_card_md(f"{it} ({window_days}d)", txt, badge=ui_metric)

    st.divider()

    # Hero trend card
    card_start("Cycle time trend", hero=True)

    if "End" not in view_df.columns or "CT" not in view_df.columns:
        st.info("No completed items to plot.")
    else:
        d = view_df[["End", "CT"] + (["IssueType"] if "IssueType" in view_df.columns else [])].copy()
        d["End"] = pd.to_datetime(d["End"], utc=True, errors="coerce")
        d = d.dropna(subset=["End", "CT"])
        if d.empty:
            st.info("No completed items to plot.")
        else:
            if mode == "Monthly":
                d["month"] = d["End"].dt.to_period("M").dt.to_timestamp("M")
                monthly = d.groupby("month", as_index=False).agg(
                    mean_ct=("CT", "mean"),
                    median_ct=("CT", "median"),
                    p85_ct=("CT", lambda x: x.quantile(0.85)),
                    count=("CT", "size"),
                )
                field = {"Median (P50)": "median_ct", "Average (Mean)": "mean_ct", "P85": "p85_ct"}[metric]

                use_fib = st.checkbox("Fibonacci performance bands (P85 only)", value=False)
                if use_fib and metric == "P85":
                    df_plot = monthly.dropna(subset=["p85_ct"]).sort_values("month")
                    dates = [pd.to_datetime(x) for x in df_plot["month"].tolist()]
                    vals = df_plot["p85_ct"].tolist()
                    st.pyplot(fib_overlay_chart(dates, vals, title=f"{selected_team} — P85 Fibonacci Trend"))
                else:
                    base = alt.Chart(monthly).encode(x=alt.X("month:T", title="Month"))
                    bars = base.mark_bar(opacity=0.15).encode(y=alt.Y("count:Q", title="Items"))
                    line = base.mark_line(point=True).encode(
                        y=alt.Y(f"{field}:Q", title=f"{metric} CT (days)"),
                        tooltip=["month:T", alt.Tooltip(field + ":Q", title="CT", format=".2f"), "count:Q"],
                    )
                    st.altair_chart((bars + line).properties(height=340), use_container_width=True)

            else:
                window = 30 if "30" in mode else 14
                # simple daily trailing window series
                end = d["End"].max().floor("D")
                start = d["End"].min().floor("D")
                idx = pd.date_range(start=start, end=end, freq="D", tz="UTC")

                field = {"Median (P50)": "median", "Average (Mean)": "mean", "P85": "p85"}[metric]
                rows = []
                for day in idx:
                    ws = day - pd.Timedelta(days=window - 1)
                    sub = d[(d["End"] >= ws) & (d["End"] <= day + pd.Timedelta(days=1) - pd.Timedelta(seconds=1))]
                    ct = sub["CT"]
                    if len(ct) == 0:
                        val = None
                    elif field == "median":
                        val = float(ct.median())
                    elif field == "mean":
                        val = float(ct.mean())
                    else:
                        val = float(ct.quantile(0.85))
                    rows.append({"date": day.to_pydatetime(), "ct": val, "count": int(len(ct))})

                r = pd.DataFrame(rows)
                base = alt.Chart(r).encode(x=alt.X("date:T", title="Date"))
                area = base.mark_area(opacity=0.10).encode(y=alt.Y("count:Q", title=f"Items (last {window}d)"))
                line = base.mark_line().encode(y=alt.Y("ct:Q", title=f"{metric} CT (days) — trailing {window}d"), tooltip=["date:T", "ct:Q", "count:Q"])
                st.altair_chart((area + line).properties(height=340), use_container_width=True)

    card_end()

    # Lower grid: outliers + quick insights
    g1, g2 = st.columns([1.35, 1])
    with g1:
        card_start(f"Slowest completed items ({window_days}d)")
        if w is None or w.empty:
            st.info("No completed items in this window.")
        else:
            cols = [c for c in ["Key", "Summary", "IssueType", "CT", "End"] if c in w.columns]
            show = w[cols].copy().sort_values("CT", ascending=False).head(15)
            show["CT"] = show["CT"].astype(float).round(1)
            st.dataframe(show.reset_index(drop=True), use_container_width=True, height=360)
        card_end()

    with g2:
        card_start("Auto insights")
        insights = []
        try:
            if v is not None:
                insights.append(f"- {metric} CT over last {window_days}d: **{v:.1f}d**")
            if rel is not None:
                insights.append(f"- Reliability (SLE) last {window_days}d: **{rel*100:.0f}%** (target 85%)")
            if not w.empty and "IssueType" in w.columns:
                top_type = w["IssueType"].value_counts().index[0]
                insights.append(f"- Most common issue type completed: **{top_type}**")
        except Exception:
            pass
        if insights:
            st.markdown("\n".join(insights))
        else:
            st.info("Not enough data for insights yet.")
        card_end()

elif page == "Setup":
    st.subheader("Setup")
    st.caption("Health check for onboarding and configuration. This page is read-only and tells you what to fix.")

    # Sign out
    if _auth_enabled():
        # Debug indicators (helps diagnose Streamlit Cloud vs localhost differences)
        with st.expander("Auth diagnostics", expanded=False):
            st.write({
                "auth_enabled": _auth_enabled(),
                "has_auth_secret": bool(_auth_secret()),
                "cookie_lib_available": EncryptedCookieManager is not None,
                "cookie_ready": (lambda: (_cookies().ready() if _cookies() is not None else False))(),
                "auth_cookie_present": _has_auth_cookie(),
            })

        if st.button("Sign out", use_container_width=True):
            st.session_state.pop("_authed", None)
            _clear_auth_cookie()
            st.success("Signed out.")
            st.rerun()

    # CSS diagnostics
    if st.session_state.get("_css_load_error"):
        st.warning(f"CSS did not load: {st.session_state['_css_load_error']}")

    st.divider()
    st.markdown("### Configuration")
    st.caption("These settings define how CTapp interprets your workflow. Changes are saved to config.json (not secrets).")

    s1, s2 = st.columns([1, 1])
    with s1:
        st.text_input("Saved Filter ID", key="cfg_filter_id")
    with s2:
        st.caption("Tip: keep one filter per environment.")

    st.markdown("#### Status buckets")
    st.text_area(
        "Rules (Bucket = Status1, Status2, ...)",
        key="cfg_rules_text",
        height=140,
    )

    st.markdown("#### Start / Done mapping (auto-detected prefixes)")
    st.caption("Fetch data once to populate status dropdowns and detect prefixes.")

    detected_prefixes = st.session_state.get("_detected_prefixes", [])
    status_options = st.session_state.get("_status_options", [])  # (name,id)
    prefix_cfg = CFG.get("prefix_status_ids", {}) or {}

    if not detected_prefixes and prefix_cfg:
        detected_prefixes = sorted(prefix_cfg.keys())

    edits = {}
    if detected_prefixes:
        for pref in detected_prefixes:
            existing = prefix_cfg.get(pref, {})
            st.markdown(f"**{pref}**")
            team_name = st.text_input(
                f"Team name ({pref})",
                value=str(existing.get("team_name", pref)),
                key=f"setup_team_{pref}",
            )

            start_id_default = str(existing.get("start") or existing.get("start_status_id") or "")
            done_id_default = str(existing.get("done") or existing.get("done_status_id") or existing.get("end") or "")

            if status_options:
                names = [n for (n, _) in status_options]
                name_by_id = {sid: name for (name, sid) in status_options}
                start_name_default = name_by_id.get(start_id_default)
                done_name_default = name_by_id.get(done_id_default)

                start_name = st.selectbox(
                    f"Start status ({pref})",
                    options=names,
                    index=(names.index(start_name_default) if start_name_default in names else 0),
                    key=f"setup_start_{pref}",
                )
                done_name = st.selectbox(
                    f"Done status ({pref})",
                    options=names,
                    index=(names.index(done_name_default) if done_name_default in names else 0),
                    key=f"setup_done_{pref}",
                )

                id_by_name = {name: sid for (name, sid) in status_options}
                start_id = id_by_name.get(start_name)
                done_id = id_by_name.get(done_name)
            else:
                start_id = st.text_input(f"Start status ID ({pref})", value=start_id_default, key=f"setup_startid_{pref}")
                done_id = st.text_input(f"Done status ID ({pref})", value=done_id_default, key=f"setup_doneid_{pref}")

            edits[pref] = {"team_name": team_name, "start": str(start_id).strip(), "done": str(done_id).strip()}
            st.divider()
    else:
        st.info("No prefixes detected yet. Click Refresh data in the top bar, then come back here.")

    if st.button("Save workflow settings", type="primary", use_container_width=True):
        new_cfg = dict(CFG)
        new_cfg["filter_id"] = str(st.session_state.get("cfg_filter_id", "")).strip()
        new_cfg["rules_text"] = str(st.session_state.get("cfg_rules_text", "")).strip()
        if edits:
            new_cfg["prefix_status_ids"] = edits
        save_config(new_cfg)
        st.success("Saved. Refreshing…")
        st.rerun()

    st.divider()

    issues = []

    # 1) API key
    has_key = bool((api_key or "").strip())
    if not has_key:
        issues.append("API key not set (add it in the sidebar, or save it to .streamlit/secrets.toml).")

    # 2) Filter ID
    if not str(filter_id or "").strip():
        issues.append("Filter ID not set.")

    # 3) Fetch / data present
    has_data = ("raw_data" in st.session_state) and (raw is not None) and (not raw.empty)
    if not has_data:
        issues.append("No data loaded. Click Fetch Data in the sidebar.")

    # 4) Prefixes detected
    prefixes = st.session_state.get("_detected_prefixes", [])
    if has_data and not prefixes:
        # fallback: infer from keys
        try:
            if "Key" in raw.columns:
                prefixes = sorted(raw["Key"].astype(str).str.split("-", n=1).str[0].dropna().unique().tolist())
        except Exception:
            prefixes = []
    if has_data and not prefixes:
        issues.append("No project prefixes detected from issue keys. Check your filter returns valid Jira keys.")

    # 5) Start/Done mapping completeness
    prefix_cfg = CFG.get("prefix_status_ids", {}) or {}
    missing_map = []
    for p in prefixes or []:
        m = prefix_cfg.get(p, {})
        if not (str(m.get("start") or "").strip() and str(m.get("done") or "").strip()):
            missing_map.append(p)
    if has_data and missing_map:
        issues.append(f"Start/Done mapping missing for prefixes: {', '.join(missing_map)} (set it in Setup → Configuration).")

    # 6) Bucket rules present
    if not str(rules_text or "").strip():
        issues.append("Status bucket rules are empty.")

    # 7) SLE thresholds
    sle = CFG.get("sle_days_by_type", None)
    if not sle:
        issues.append("SLE thresholds not saved yet. Go to Reliability (SLE) and click Save SLE thresholds.")

    # 8) Events saved
    events_path = os.path.join(os.path.dirname(__file__), "context_events.csv")
    events_count = 0
    if os.path.exists(events_path):
        try:
            events_count = int(pd.read_csv(events_path).shape[0])
        except Exception:
            events_count = 0

    # --- Display ---
    st.markdown("### Status")
    s1, s2, s3, s4 = st.columns(4)
    s1.metric("API key", "OK" if has_key else "Missing")
    s2.metric("Filter ID", "OK" if str(filter_id or "").strip() else "Missing")
    s3.metric("Data loaded", "OK" if has_data else "Missing")
    s4.metric("Saved events", f"{events_count}")

    st.markdown("### Detected prefixes")
    st.write(prefixes if prefixes else "—")

    st.markdown("### Issues to fix")
    if not issues:
        st.success("All core setup checks look good.")
    else:
        for it in issues:
            st.error(it)

    st.divider()

    # Support bundle (no API key)
    st.markdown("### Support bundle")
    st.caption("Exports local config + events + minimal diagnostics. Does not include your API key.")

    bundle = {
        "diagnostics": {
            "has_data": has_data,
            "row_count": int(len(raw)) if has_data else 0,
            "detected_prefixes": prefixes,
            "bucket_columns": [c for c in (raw.columns.tolist() if has_data else []) if c not in ("Key","Summary","Team","IssueType","Sprint","Start","End","CT","_bucketer") and pd.api.types.is_numeric_dtype(raw[c])],
        },
        "config": {k: v for k, v in (CFG or {}).items() if k != "TIMEPIECE_API_KEY"},
    }

    # attach events if present
    try:
        if os.path.exists(events_path):
            bundle["events_csv"] = pd.read_csv(events_path).to_dict(orient="records")
    except Exception:
        pass

    st.download_button(
        "Download support bundle (JSON)",
        data=json.dumps(bundle, indent=2).encode("utf-8"),
        file_name="ctapp_support_bundle.json",
        mime="application/json",
        use_container_width=True,
    )


elif page == "Report Pack":
    st.subheader("Report Pack")
    st.caption("Generate exports and a leadership-ready summary for the current team selection.")

    # Helper: download button for a dataframe
    def _dl_df(label: str, df: pd.DataFrame, filename: str):
        if df is None or df.empty:
            st.download_button(label, data=b"", file_name=filename, disabled=True, use_container_width=True)
            return
        st.download_button(
            label,
            data=df.to_csv(index=False).encode("utf-8"),
            file_name=filename,
            mime="text/csv",
            use_container_width=True,
        )

    # --- Core metrics reused in pack + printable report ---
    avg_ct = float(view_df["CT"].mean()) if "CT" in view_df.columns and view_df["CT"].notna().any() else None
    p85_ct = float(view_df["CT"].quantile(0.85)) if "CT" in view_df.columns and view_df["CT"].notna().any() else None

    default_sle = {"Story": 10, "Bug": 5, "Task": 8, "Spike": 12}
    sle_map = dict(default_sle)
    sle_map.update(CFG.get("sle_days_by_type", {}) or {})

    rel30 = None
    breaches30 = pd.DataFrame()
    d30_eval = pd.DataFrame()
    try:
        if all(c in view_df.columns for c in ["End", "CT", "IssueType"]):
            dd = view_df[["Key", "Summary", "IssueType", "CT", "End"]].copy()
            dd["End"] = pd.to_datetime(dd["End"], utc=True, errors="coerce")
            dd = dd.dropna(subset=["End", "CT", "IssueType"])
            if not dd.empty:
                end_max = dd["End"].max()
                start_30 = end_max - pd.Timedelta(days=30)
                d30 = dd[(dd["End"] >= start_30) & (dd["End"] <= end_max)].copy()
                d30["SLE_days"] = d30["IssueType"].astype(str).map(sle_map)
                d30 = d30.dropna(subset=["SLE_days"])
                if not d30.empty:
                    d30["within_sle"] = d30["CT"].astype(float) <= d30["SLE_days"].astype(float)
                    rel30 = float(d30["within_sle"].mean())
                    breaches30 = d30[~d30["within_sle"]].copy()
                    d30_eval = d30.copy()
    except Exception:
        pass

    # Risks snapshot (WIP)
    wip_export = pd.DataFrame()
    try:
        if "Start" in view_df.columns:
            wd = view_df.copy()
            wd["Start"] = pd.to_datetime(wd["Start"], utc=True, errors="coerce")
            wd["End"] = pd.to_datetime(wd["End"], utc=True, errors="coerce") if "End" in wd.columns else pd.NaT
            wip = wd[wd["Start"].notna() & wd["End"].isna()].copy()
            if not wip.empty:
                now = pd.Timestamp.now(tz="UTC")
                wip["Age_days"] = ((now - wip["Start"]).dt.total_seconds() / 86400.0).round(1)
                wip["SLE_days"] = wip.get("IssueType").astype(str).map(sle_map)
                wip_export = wip[[c for c in ["Key", "Summary", "Team", "IssueType", "Start", "Age_days", "SLE_days"] if c in wip.columns]]
    except Exception:
        pass

    # Monthly CT series
    monthly_export = pd.DataFrame()
    try:
        if "End" in view_df.columns and "CT" in view_df.columns:
            md = view_df[["End", "CT"]].copy()
            md["End"] = pd.to_datetime(md["End"], utc=True, errors="coerce")
            md = md.dropna(subset=["End", "CT"])
            if not md.empty:
                md["month"] = md["End"].dt.to_period("M").dt.to_timestamp("M")
                monthly_export = md.groupby("month", as_index=False).agg(
                    mean_ct=("CT", "mean"),
                    median_ct=("CT", "median"),
                    p85_ct=("CT", lambda x: x.quantile(0.85)),
                    count=("CT", "size"),
                )
    except Exception:
        monthly_export = pd.DataFrame()

    # --- Leadership summary panel ---
    st.markdown("### Leadership summary")
    lines = []
    lines.append(f"- Scope: **{selected_team}**")
    if avg_ct is not None:
        lines.append(f"- Average cycle time: **{avg_ct:.1f} days**")
    if p85_ct is not None:
        lines.append(f"- P85 cycle time: **{p85_ct:.1f} days**")
    if rel30 is not None:
        lines.append(f"- Reliability (last 30d) vs SLE: **{rel30*100:.0f}%** (target 85%)")
    if not wip_export.empty:
        lines.append(f"- In-flight items (WIP): **{len(wip_export)}**")
    st.markdown("\n".join(lines))

    # --- Printable HTML report ---
    st.divider()
    st.markdown("### Printable leadership report")
    report_title = st.text_input("Report title", value="Flow Metrics — Leadership Summary")
    author = st.text_input("Prepared by", value=str(CFG.get("report_prepared_by", "")))
    note = st.text_area("Notes / narrative (optional)", value="", height=90)

    # Small tables for report
    breaches_small = breaches30[[c for c in ["Key", "Summary", "IssueType", "CT", "SLE_days", "End"] if c in breaches30.columns]].copy() if not breaches30.empty else pd.DataFrame()
    if not breaches_small.empty:
        breaches_small = breaches_small.sort_values("CT", ascending=False).head(15)
        breaches_small["CT"] = breaches_small["CT"].astype(float).round(1)

    wip_small = wip_export.copy()
    if not wip_small.empty and "Age_days" in wip_small.columns:
        wip_small = wip_small.sort_values("Age_days", ascending=False).head(15)

    def _df_to_html_table(df: pd.DataFrame) -> str:
        if df is None or df.empty:
            return "<div class='muted'>None</div>"
        return df.to_html(index=False, escape=True)

    # --- Inline SVG charts (optional; requires vl-convert-python) ---
    def _chart_to_svg_data_uri(chart: alt.Chart) -> str | None:
        try:
            svg = chart.to_svg()  # requires vl-convert-python
            b64 = base64.b64encode(svg.encode("utf-8")).decode("ascii")
            return f"data:image/svg+xml;base64,{b64}"
        except Exception:
            return None

    ct_svg_uri = None
    if monthly_export is not None and not monthly_export.empty and "month" in monthly_export.columns:
        ct_chart = (
            alt.Chart(monthly_export)
            .mark_line(point=True)
            .encode(
                x=alt.X("month:T", title="Month"),
                y=alt.Y("median_ct:Q", title="Median CT (days)"),
                tooltip=["month:T", alt.Tooltip("median_ct:Q", format=".2f"), "count:Q"],
            )
            .properties(width=680, height=220, title="Cycle time (Median) — monthly")
        )
        ct_svg_uri = _chart_to_svg_data_uri(ct_chart)

    rel_svg_uri = None
    try:
        if "End" in view_df.columns and "CT" in view_df.columns and "IssueType" in view_df.columns:
            rr = view_df[["End", "CT", "IssueType"]].copy()
            rr["End"] = pd.to_datetime(rr["End"], utc=True, errors="coerce")
            rr = rr.dropna(subset=["End", "CT", "IssueType"])
            rr["SLE_days"] = rr["IssueType"].astype(str).map(sle_map)
            rr = rr.dropna(subset=["SLE_days"])
            if not rr.empty:
                rr["within_sle"] = rr["CT"].astype(float) <= rr["SLE_days"].astype(float)
                rr["month"] = rr["End"].dt.to_period("M").dt.to_timestamp("M")
                rm = rr.groupby("month", as_index=False).agg(reliability=("within_sle", "mean"), count=("within_sle", "size")).sort_values("month")
                rel_chart = (
                    alt.Chart(rm)
                    .mark_line(point=True)
                    .encode(
                        x=alt.X("month:T", title="Month"),
                        y=alt.Y("reliability:Q", title="Reliability", axis=alt.Axis(format="%"), scale=alt.Scale(domain=[0, 1])),
                        tooltip=["month:T", alt.Tooltip("reliability:Q", format=".0%"), "count:Q"],
                    )
                    .properties(width=680, height=220, title="Reliability vs SLE — monthly")
                )
                target = alt.Chart(pd.DataFrame({"y": [0.85]})).mark_rule(strokeDash=[6, 4], color="#22D3EE", opacity=0.9).encode(y="y:Q")
                rel_svg_uri = _chart_to_svg_data_uri(rel_chart + target)
    except Exception:
        rel_svg_uri = None

    charts_note = ""
    if ct_svg_uri is None or rel_svg_uri is None:
        charts_note = "<div class='muted'>Charts unavailable (SVG export requires vl-convert-python). You can still use the CSV exports.</div>"

    generated_on = datetime.datetime.now().strftime("%d %b %Y %H:%M")

    html = f"""
<!doctype html>
<html>
<head>
<meta charset='utf-8'/>
<title>{report_title}</title>
<style>
  body {{ font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif; margin: 28px; color:#111827; }}
  .header {{ display:flex; justify-content:space-between; align-items:flex-end; border-bottom:2px solid #e5e7eb; padding-bottom:12px; margin-bottom:18px; }}
  .title {{ font-size: 20px; font-weight: 700; }}
  .meta {{ font-size: 12px; color:#6b7280; text-align:right; }}
  .kpis {{ display:grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 14px 0 22px; }}
  .kpi {{ border:1px solid #e5e7eb; border-radius:12px; padding:12px; }}
  .kpi .label {{ font-size:12px; color:#6b7280; }}
  .kpi .value {{ font-size:18px; font-weight:700; margin-top:6px; }}
  h2 {{ font-size: 14px; margin-top: 18px; }}
  .muted {{ color:#6b7280; font-size:12px; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 8px; }}
  th, td {{ border: 1px solid #e5e7eb; padding: 8px; font-size: 12px; vertical-align: top; }}
  th {{ background:#f9fafb; text-align:left; }}
  .note {{ white-space: pre-wrap; border:1px solid #e5e7eb; border-radius:12px; padding:12px; background:#fafafa; font-size:12px; }}
  .chart {{ border:1px solid #e5e7eb; border-radius:12px; padding:10px; margin-top: 10px; }}
  .chart img {{ width:100%; height:auto; }}
  @media print {{
    body {{ margin: 12mm; }}
    .kpis {{ grid-template-columns: repeat(2, 1fr); }}
  }}
</style>
</head>
<body>
  <div class='header'>
    <div class='title'>{report_title}</div>
    <div class='meta'>
      <div><b>Scope:</b> {selected_team}</div>
      <div><b>Generated:</b> {generated_on}</div>
      <div><b>Prepared by:</b> {author if author else "—"}</div>
    </div>
  </div>

  <div class='kpis'>
    <div class='kpi'><div class='label'>Average cycle time</div><div class='value'>{("%.1f days"%avg_ct) if avg_ct is not None else "—"}</div></div>
    <div class='kpi'><div class='label'>P85 cycle time</div><div class='value'>{("%.1f days"%p85_ct) if p85_ct is not None else "—"}</div></div>
    <div class='kpi'><div class='label'>Reliability (last 30d)</div><div class='value'>{(f"{rel30*100:.0f}%") if rel30 is not None else "—"}</div><div class='muted'>Target: 85%</div></div>
    <div class='kpi'><div class='label'>WIP items</div><div class='value'>{len(wip_export) if wip_export is not None and not wip_export.empty else 0}</div></div>
  </div>

  <h2>Trends</h2>
  {charts_note}
  {f"<div class='chart'><img alt='Cycle time trend' src='{ct_svg_uri}'/></div>" if ct_svg_uri else ""}
  {f"<div class='chart'><img alt='Reliability trend' src='{rel_svg_uri}'/></div>" if rel_svg_uri else ""}

  <h2>Notes</h2>
  <div class='note'>{note if note.strip() else "(none)"}</div>

  <h2>SLE breaches (last 30d)</h2>
  {_df_to_html_table(breaches_small)}

  <h2>Top aging WIP (in-flight)</h2>
  {_df_to_html_table(wip_small)}

  <p class='muted'>Generated by CTapp.</p>
</body>
</html>
"""

    st.download_button(
        "Download printable HTML report",
        data=html.encode("utf-8"),
        file_name="ctapp_leadership_report.html",
        mime="text/html",
        use_container_width=True,
    )

    # --- Exports ---
    st.divider()
    st.markdown("### Exports")
    c1, c2, c3 = st.columns(3)

    _dl_df("Export raw data (current selection)", view_df, "ctapp_raw_current_selection.csv")

    with c1:
        _dl_df("Export SLE breaches (last 30d)", breaches30[[c for c in ["Key", "Summary", "IssueType", "CT", "SLE_days", "End"] if c in breaches30.columns]], "ctapp_sle_breaches_last30d.csv")
    with c2:
        _dl_df("Export WIP (aging)", wip_export, "ctapp_wip_aging.csv")
    with c3:
        _dl_df("Export monthly CT series", monthly_export, "ctapp_monthly_ct_series.csv")

    st.caption("Tip: download the HTML report, open it in a browser, and use Print → Save as PDF for a client-ready deliverable.")

elif page == "Team::Slowest Items":
    st.subheader("Slowest Items")
    if view_df.empty or "CT" not in view_df.columns or "_bucketer" not in view_df.columns:
        st.info("No data available.")
    else:
        th = view_df["_bucketer"].dt.to_period("M")
        p85 = view_df.groupby(th)["CT"].quantile(0.85).rename("p85")
        merged = view_df.join(p85, on=th)
        slow = merged[merged["CT"] > merged["p85"]].copy()

        if slow.empty:
            st.info("No items above the 85th percentile.")
        else:
            st.dataframe(
                slow[[c for c in ["Key", "Summary", "Team", "CT", "Start", "End"] if c in slow.columns]]
                .sort_values("CT", ascending=False)
                .head(200),
                use_container_width=True,
            )

elif page == "Team::Forecasting":
    st.subheader("Monte Carlo Forecasting (Throughput Based)")
    if view_df.empty or view_df.get("_bucketer").dropna().empty:
        st.info("No completion data available for forecasting.")
    else:
        throughput = (
            view_df["_bucketer"].dropna().dt.to_period("W").value_counts().values
        )
        if len(throughput) == 0:
            st.info("Not enough throughput data.")
        else:
            mode = st.radio("Forecast mode", ["How many items in N weeks?", "When will X items be done?"], index=0)
            start_date = st.date_input("Start date", datetime.date.today())

            if mode == "How many items in N weeks?":
                weeks = int(st.number_input("Weeks", min_value=1, max_value=52, value=4))
                sims = int(st.number_input("Simulations", min_value=1000, max_value=50000, value=10000, step=1000))
                results = []
                for _ in range(sims):
                    total_done = 0
                    for _ in range(weeks):
                        total_done += int(np.random.choice(throughput))
                    results.append(total_done)
                p50, p85, p95 = np.percentile(results, [50, 85, 95])
                st.write(f"In {weeks} weeks (starting {start_date:%d %b %Y}):")
                st.write(f"- **50% likely**: {int(p50)} items")
                st.write(f"- **85% likely**: {int(p85)} items")
                st.write(f"- **95% likely**: {int(p95)} items")
                st.altair_chart(
                    alt.Chart(pd.DataFrame({"Items Delivered": results}))
                    .mark_bar()
                    .encode(alt.X("Items Delivered:Q", bin=alt.Bin(maxbins=30)), y="count()")
                    ,
                    use_container_width=True,
                )
            else:
                items = int(st.number_input("Number of items", min_value=1, max_value=200, value=10))
                sims = int(st.number_input("Simulations", min_value=1000, max_value=50000, value=10000, step=1000))
                results = []
                for _ in range(sims):
                    total_done = 0
                    week_count = 0
                    while total_done < items:
                        total_done += int(np.random.choice(throughput))
                        week_count += 1
                    results.append(week_count * 7)
                p50, p85, p95 = np.percentile(results, [50, 85, 95])
                st.write(f"To deliver {items} items (starting {start_date:%d %b %Y}):")
                st.write(f"- **50% likely**: {(start_date + datetime.timedelta(days=float(p50))):%d %b %Y}")
                st.write(f"- **85% likely**: {(start_date + datetime.timedelta(days=float(p85))):%d %b %Y}")
                st.write(f"- **95% likely**: {(start_date + datetime.timedelta(days=float(p95))):%d %b %Y}")
                st.altair_chart(
                    alt.Chart(pd.DataFrame({"Days to Complete": results}))
                    .mark_bar()
                    .encode(alt.X("Days to Complete:Q", bin=alt.Bin(maxbins=30)), y="count()")
                    ,
                    use_container_width=True,
                )

elif page == "Team::Sprints":
    st.subheader("Sprint Analysis")

    df_src = view_df
    if df_src is None or df_src.empty or "Sprint" not in df_src.columns or "IssueType" not in df_src.columns:
        st.info("No sprint/issue type data available.")
    else:
        expanded = df_src.copy()
        expanded["Sprint"] = expanded["Sprint"].fillna("")
        expanded = expanded.assign(Sprint=expanded["Sprint"].astype(str).str.split(","))
        expanded = expanded.explode("Sprint")
        expanded["Sprint"] = expanded["Sprint"].astype(str).str.strip()
        expanded = expanded[expanded["Sprint"] != ""]

        if expanded.empty:
            st.info("No sprint data after expansion.")
        else:
            end_col = "End" if "End" in expanded.columns else None
            expanded["_enddate"] = pd.to_datetime(expanded[end_col], errors="coerce") if end_col else pd.NaT

            sprint_order = (
                expanded.groupby("Sprint")["_enddate"].max().sort_values(ascending=False).index.tolist()
            )

            expanded["IssueType"] = expanded["IssueType"].fillna("Unknown")

            grouped = expanded.groupby(["Sprint", "IssueType"]).size().reset_index(name="Count")
            totals = expanded.groupby("Sprint").size().reset_index(name="Total")
            merged = pd.merge(grouped, totals, on="Sprint", how="left")
            merged["Percent"] = (merged["Count"] / merged["Total"] * 100)

            ORDER = {"Story": 0, "Bug": 1, "Spike": 2, "Task": 3}

            def make_compact(group):
                dct = dict(zip(group["IssueType"], group["Percent"]))
                parts = []
                for it in ["Story", "Bug", "Spike", "Task"]:
                    if it in dct:
                        parts.append(f"{it}: {dct[it]:.0f}%")
                extras = sorted([k for k in dct.keys() if k not in ORDER])
                for it in extras:
                    parts.append(f"{it}: {dct[it]:.0f}%")
                return ", ".join(parts)

            compact = (
                merged.groupby("Sprint").apply(make_compact).rename("Composition").reindex(sprint_order)
            )

            st.markdown("**Sprint breakdown — click a sprint to expand**")
            for spr in sprint_order:
                sprint_items = expanded[expanded["Sprint"] == spr]
                sprint_p85_text = ""
                if not sprint_items.empty and "CT" in sprint_items.columns:
                    sprint_p85 = sprint_items["CT"].quantile(0.85)
                    sprint_p85_text = f" • 85th CT: {sprint_p85:.1f} days"

                label = f"{spr} — {compact.get(spr, '')}{sprint_p85_text}"

                with st.expander(label):
                    spr_total = int(totals[totals["Sprint"] == spr]["Total"].iloc[0]) if spr in totals["Sprint"].values else 0
                    st.caption(f"Total items: {spr_total}")

                    g = merged[merged["Sprint"] == spr].copy()
                    g["order_key"] = g["IssueType"].map(ORDER).fillna(99)
                    g = g.sort_values(["order_key", "IssueType"]).drop(columns=["order_key"])
                    g["Percent"] = g["Percent"].round(1)

                    p85_by_type = sprint_items.groupby("IssueType")["CT"].quantile(0.85) if "CT" in sprint_items.columns else {}
                    g["85th CT (days)"] = g["IssueType"].map(p85_by_type).round(2)

                    st.dataframe(
                        g[["IssueType", "Count", "Percent", "85th CT (days)"]].reset_index(drop=True),
                        use_container_width=True,
                    )

                    st.markdown("**Items by Issue Type**")
                    has_key_col = "Key" in sprint_items.columns
                    has_summary_col = "Summary" in sprint_items.columns

                    for itype in g["IssueType"].unique():
                        sub_items = sprint_items[sprint_items["IssueType"] == itype].copy()
                        if sub_items.empty:
                            continue
                        title = f"{itype} ({len(sub_items)} items)"
                        with st.expander(title):
                            cols_to_show = []
                            if has_key_col:
                                cols_to_show.append("Key")
                            if has_summary_col:
                                cols_to_show.append("Summary")
                            for col in ["IssueType", "CT", "Start", "End"]:
                                if col in sub_items.columns and col not in cols_to_show:
                                    cols_to_show.append(col)
                            st.dataframe(
                                sub_items[cols_to_show].sort_values("CT", ascending=False).reset_index(drop=True),
                                use_container_width=True,
                            )

elif page == "Events":
    st.subheader("Events")
    st.caption("Overlay flow metrics with real-world events (role changes, holidays, major releases) to understand impacts on team performance.")

    if raw is None or raw.empty or "Team" not in raw.columns:
        st.info("Fetch data first.")
    else:
        # ---- Controls ----
        st.markdown("### Controls")
        c1, c2, c3 = st.columns([1.2, 1.2, 1.6])

        metric_choice = c1.selectbox("Metric", ["Median (P50)", "Average (Mean)", "P85"], index=2, key="events_metric_main")
        view_choice = c2.selectbox("Grouping", ["Monthly"], index=0, key="events_grouping")

        all_teams = sorted([t for t in raw["Team"].dropna().astype(str).unique().tolist() if t])
        default_team_order = [t for t in ["Team 1", "Team 2", "Team 4"] if t in all_teams]
        default_sel = default_team_order if default_team_order else all_teams[:3]
        teams_sel = c3.multiselect("Teams", options=all_teams, default=default_sel)

        metric_field = {"Median (P50)": "median_ct", "Average (Mean)": "mean_ct", "P85": "p85_ct"}[metric_choice]
        metric_title = {"Median (P50)": "Median CT (days)", "Average (Mean)": "Average CT (days)", "P85": "P85 CT (days)"}[metric_choice]

        st.divider()

        # ---- Events input ----
        st.markdown("### Events")
        st.caption("Add events like 'Developer left', 'PO changed', 'Major release' and see them overlaid on each team's chart.")

        st.markdown(
            """
**CSV format**
- Required: `team`, `start_date`
- Optional: `end_date`, `event_type`, `who`, `description`

If `end_date` is provided, the event is shown as a shaded period; otherwise it is a vertical marker.
"""
        )

        # Persisted context events (saved locally)
        CONTEXT_EVENTS_PATH = os.path.join(os.path.dirname(__file__), "context_events.csv")

        def _load_context_events() -> pd.DataFrame:
            cols_keep = ["Team", "Start", "End", "EventType", "Who", "Description"]
            if os.path.exists(CONTEXT_EVENTS_PATH):
                try:
                    df = pd.read_csv(
                        CONTEXT_EVENTS_PATH,
                        dtype={"Team": "string", "EventType": "string", "Who": "string", "Description": "string"},
                    )
                    for c in cols_keep:
                        if c not in df.columns:
                            df[c] = "" if c in ("Team", "EventType", "Who", "Description") else pd.NaT
                    df = df[cols_keep]
                    df["Start"] = pd.to_datetime(df["Start"], errors="coerce")
                    df["End"] = pd.to_datetime(df["End"], errors="coerce")
                    return df
                except Exception:
                    pass
            return pd.DataFrame(columns=cols_keep)

        def _save_context_events(df: pd.DataFrame) -> None:
            cols_keep = ["Team", "Start", "End", "EventType", "Who", "Description"]
            out = df.copy() if df is not None else pd.DataFrame(columns=cols_keep)
            for c in cols_keep:
                if c not in out.columns:
                    out[c] = "" if c in ("Team", "EventType", "Who", "Description") else pd.NaT
            out = out[cols_keep]
            out.to_csv(CONTEXT_EVENTS_PATH, index=False)

        st.markdown("#### Save / load")
        cctx1, cctx2, cctx3 = st.columns([1.2, 1.2, 1.6])

        # Export current saved events
        saved_df = _load_context_events()
        cctx1.download_button(
            "Export saved events CSV",
            data=saved_df.to_csv(index=False).encode("utf-8"),
            file_name="ctapp_context_events.csv",
            mime="text/csv",
            use_container_width=True,
        )

        if cctx2.button("Clear saved events", use_container_width=True):
            _save_context_events(pd.DataFrame(columns=["Team", "Start", "End", "EventType", "Who", "Description"]))
            st.success("Cleared. Rerun to refresh.")
            st.rerun()

        cctx3.caption("Events are only saved when you click 'Save events now'.")

        # Start with persisted events
        ctx_df = saved_df.copy()

        # Allow editing / manual entry
        st.markdown("#### Edit / add events")
        st.caption("Tip: click into a cell to edit. Add new rows at the bottom.")

        # Ensure all expected columns exist + force text columns to string (prevents Streamlit inferring numeric editors)
        for c in ["Team", "Start", "End", "EventType", "Who", "Description"]:
            if c not in ctx_df.columns:
                ctx_df[c] = "" if c in ("Team", "EventType", "Who", "Description") else pd.NaT

        for c in ["Team", "EventType", "Who", "Description"]:
            ctx_df[c] = ctx_df[c].astype("string").fillna("")

        # Provide friendly editors
        common_types = ["Joined Team", "Left Team", "External Distraction", "Holiday"]
        try:
            ctx_df = st.data_editor(
                ctx_df[["Team", "Start", "End", "EventType", "Who", "Description"]],
                num_rows="dynamic",
                use_container_width=True,
                column_config={
                    "Team": st.column_config.SelectboxColumn("Team", options=all_teams),
                    "Start": st.column_config.DatetimeColumn("Start"),
                    "End": st.column_config.DatetimeColumn("End"),
                    "EventType": st.column_config.SelectboxColumn("EventType", options=common_types),
                    "Who": st.column_config.TextColumn("Who"),
                    "Description": st.column_config.TextColumn("Description"),
                },
            )
        except Exception:
            ctx_df = st.data_editor(ctx_df, num_rows="dynamic", use_container_width=True)

        # Normalise types so charts work reliably
        ctx_df["Team"] = ctx_df["Team"].astype(str).str.strip()
        ctx_df["EventType"] = ctx_df["EventType"].astype(str).str.strip().replace({"": "Event", "nan": "Event"})
        ctx_df["Who"] = ctx_df["Who"].astype(str).replace({"nan": ""}).str.strip()
        ctx_df["Description"] = ctx_df["Description"].astype(str).replace({"nan": ""}).str.strip()
        ctx_df["Start"] = pd.to_datetime(ctx_df["Start"], errors="coerce")
        ctx_df["End"] = pd.to_datetime(ctx_df["End"], errors="coerce")
        ctx_df = ctx_df.dropna(subset=["Start"])

        # Persist edits
        csave_a, csave_b = st.columns([1, 2])
        if csave_a.button("Save events now", type="primary"):
            _save_context_events(ctx_df)
            st.success("Saved to context_events.csv")
        csave_b.caption("Events are stored locally in CTapp/context_events.csv.")

        st.divider()

        # ---- Impact view ----
        st.markdown("### Event impact view")
        st.caption("Select an event to compare performance before vs after the event date (or event period).")

        if ctx_df is None or ctx_df.empty:
            st.info("Add at least one event to use the impact view.")
        else:
            # Build a friendly selector label
            ctx_df2 = ctx_df.copy().reset_index(drop=True)
            ctx_df2["_label"] = ctx_df2.apply(
                lambda r: f"{r['Team']} | {pd.to_datetime(r['Start']).date()}" + (f"→{pd.to_datetime(r['End']).date()}" if pd.notna(r.get('End')) else "") + f" | {r.get('EventType','')}" + (f" | {r.get('Who','')}" if str(r.get('Who','')).strip() else "") + (f" — {r.get('Description','')}" if str(r.get('Description','')).strip() else ""),
                axis=1,
            )

            e1, e2, e3 = st.columns([2.2, 1, 1.2])
            event_idx = e1.selectbox("Event", options=list(ctx_df2.index), format_func=lambda i: ctx_df2.loc[i, "_label"], index=0, key="impact_event")
            window_days = int(e2.number_input("Window (days)", min_value=7, max_value=180, value=30, step=7, key="impact_window"))
            metric_choice2 = e3.selectbox("Metric", ["Median (P50)", "Average (Mean)", "P85"], index=2, key="impact_metric")

            # Determine comparison windows
            ev = ctx_df2.loc[event_idx]
            team = str(ev["Team"]).strip()
            start = pd.to_datetime(ev["Start"], errors="coerce")
            end = pd.to_datetime(ev.get("End"), errors="coerce")
            post_anchor = end if pd.notna(end) else start

            if pd.isna(start):
                st.warning("Selected event has no valid Start date.")
            else:
                pre_start = start - pd.Timedelta(days=window_days)
                pre_end = start
                post_start = post_anchor
                post_end = post_anchor + pd.Timedelta(days=window_days)

                # Completed items dataset for the selected team
                if "End" in raw.columns and "CT" in raw.columns and "Team" in raw.columns:
                    comp = raw.dropna(subset=["End", "CT"]).copy()
                    comp["End"] = pd.to_datetime(comp["End"], utc=True, errors="coerce")
                    comp = comp.dropna(subset=["End", "CT"])
                    comp_team = comp[comp["Team"].astype(str) == team].copy()
                else:
                    comp_team = pd.DataFrame()

                # Apply windows (by completion date)
                pre = comp_team[(comp_team["End"] >= pre_start.tz_localize("UTC") if pre_start.tzinfo is None else comp_team["End"] >= pre_start) & (comp_team["End"] < (pre_end.tz_localize("UTC") if pre_end.tzinfo is None else pre_end))].copy() if not comp_team.empty else pd.DataFrame()
                post = comp_team[(comp_team["End"] >= (post_start.tz_localize("UTC") if post_start.tzinfo is None else post_start)) & (comp_team["End"] < (post_end.tz_localize("UTC") if post_end.tzinfo is None else post_end))].copy() if not comp_team.empty else pd.DataFrame()

                def _calc(df: pd.DataFrame):
                    if df is None or df.empty:
                        return {"n": 0, "metric": None, "throughput": 0, "reliability": None}
                    vals = df["CT"].astype(float)
                    if metric_choice2 == "Median (P50)":
                        m = float(vals.median())
                    elif metric_choice2 == "Average (Mean)":
                        m = float(vals.mean())
                    else:
                        m = float(vals.quantile(0.85))

                    # throughput = count of completed items in window
                    tp = int(len(df))

                    # reliability using SLE thresholds (if IssueType present)
                    rel = None
                    if "IssueType" in df.columns:
                        default_sle = {"Story": 10, "Bug": 5, "Task": 8, "Spike": 12}
                        sle_map = dict(default_sle)
                        sle_map.update(CFG.get("sle_days_by_type", {}) or {})
                        tmp = df[["CT", "IssueType"]].dropna().copy()
                        tmp["SLE_days"] = tmp["IssueType"].astype(str).map(sle_map)
                        tmp = tmp.dropna(subset=["SLE_days"])
                        if not tmp.empty:
                            rel = float((tmp["CT"].astype(float) <= tmp["SLE_days"].astype(float)).mean())
                    return {"n": tp, "metric": m, "throughput": tp, "reliability": rel}

                pre_stats = _calc(pre)
                post_stats = _calc(post)

                k1, k2, k3, k4 = st.columns(4)
                k1.metric("Pre window items", f"{pre_stats['n']}")
                k2.metric("Post window items", f"{post_stats['n']}")

                def _fmt(v):
                    return "—" if v is None or (isinstance(v, float) and np.isnan(v)) else f"{v:.1f} d"

                pre_m = pre_stats["metric"]; post_m = post_stats["metric"]
                delta = None if (pre_m is None or post_m is None) else float(post_m - pre_m)
                k3.metric(f"{metric_choice2} pre", _fmt(pre_m))
                k4.metric(f"{metric_choice2} post (Δ)", "—" if post_m is None else f"{post_m:.1f} d ({delta:+.1f} d)" if delta is not None else f"{post_m:.1f} d")

                r1, r2, r3 = st.columns(3)
                pre_rel = pre_stats["reliability"]; post_rel = post_stats["reliability"]
                r1.metric("Reliability pre", "—" if pre_rel is None else f"{pre_rel*100:.0f}%")
                r2.metric("Reliability post", "—" if post_rel is None else f"{post_rel*100:.0f}%")
                if pre_rel is not None and post_rel is not None:
                    r3.metric("Reliability Δ", f"{(post_rel-pre_rel)*100:+.0f}%")
                else:
                    r3.metric("Reliability Δ", "—")

                st.caption(f"Pre window: {pre_start.date()} → {pre_end.date()} | Post window: {post_start.date()} → {post_end.date()} (by completion date)")

        st.divider()

        # ---- Build monthly CT series per team ----
        st.markdown("### Team performance with event overlays")

        if not teams_sel:
            st.info("Select at least one team.")
        else:
            d = raw.dropna(subset=["End", "CT"]).copy() if "End" in raw.columns and "CT" in raw.columns else pd.DataFrame()
            if d.empty:
                st.info("No completed items to chart (missing End/CT).")
            else:
                d["End"] = pd.to_datetime(d["End"], utc=True, errors="coerce")
                d = d.dropna(subset=["End", "CT"])
                d["Month"] = d["End"].dt.to_period("M").dt.to_timestamp("M")

                monthly = (
                    d.groupby(["Team", "Month"], as_index=False)
                    .agg(
                        mean_ct=("CT", "mean"),
                        median_ct=("CT", "median"),
                        p85_ct=("CT", lambda x: x.quantile(0.85)),
                        count=("CT", "size"),
                    )
                )

                monthly = monthly[monthly["Team"].isin(teams_sel)].copy()
                if monthly.empty:
                    st.info("No data for the selected teams.")
                else:
                    # Build one chart per team (avoids Altair facet restrictions when layering different data sources)
                    team_ctx_all = ctx_df.copy() if ctx_df is not None else pd.DataFrame()
                    if team_ctx_all is not None and not team_ctx_all.empty:
                        team_ctx_all = team_ctx_all[team_ctx_all["Team"].isin(teams_sel)]

                    for team in teams_sel:
                        st.markdown(f"#### {team}")
                        mteam = monthly[monthly["Team"] == team].copy()
                        if mteam.empty:
                            st.info("No completed items to chart for this team.")
                            continue

                        base = alt.Chart(mteam).encode(
                            x=alt.X("Month:T", title="Month"),
                            y=alt.Y(f"{metric_field}:Q", title=metric_title),
                            tooltip=[
                                alt.Tooltip("Month:T"),
                                alt.Tooltip(f"{metric_field}:Q", title=metric_title, format=".2f"),
                                alt.Tooltip("count:Q", title="Items"),
                            ],
                        )

                        line = base.mark_line(point=True, color="#22D3EE").properties(height=240)
                        layers = [line]

                        if team_ctx_all is not None and not team_ctx_all.empty:
                            tctx = team_ctx_all[team_ctx_all["Team"] == team].copy()
                            if not tctx.empty:
                                periods = tctx[tctx["End"].notna()].copy()
                                instants = tctx[tctx["End"].isna()].copy()

                                if not periods.empty:
                                    rect = alt.Chart(periods).mark_rect(opacity=0.12).encode(
                                        x=alt.X("Start:T"),
                                        x2=alt.X2("End:T"),
                                        color=alt.Color("EventType:N"),
                                        tooltip=["EventType:N", "Who:N", "Description:N", "Start:T", "End:T"],
                                    )
                                    layers.append(rect)

                                if not instants.empty:
                                    rules = alt.Chart(instants).mark_rule(strokeDash=[5, 5], size=2).encode(
                                        x="Start:T",
                                        color=alt.Color("EventType:N"),
                                        tooltip=["EventType:N", "Who:N", "Description:N", "Start:T"],
                                    )
                                    layers.append(rules)

                        st.altair_chart(alt.layer(*layers).resolve_scale(y="independent"), use_container_width=True)

        st.divider()

        # ---- Events heatmap ----
        st.markdown("### Events heatmap")
        if ctx_df is None or ctx_df.empty:
            st.info("Add or upload events to see the heatmap.")
        else:
            ctx_df2 = ctx_df.copy()
            ctx_df2["Month"] = pd.to_datetime(ctx_df2["Start"], errors="coerce").dt.to_period("M").dt.to_timestamp()
            heat = ctx_df2.dropna(subset=["Month"]).groupby(["Team", "Month"]).size().reset_index(name="Events")
            heat = heat[heat["Team"].isin(teams_sel)] if teams_sel else heat
            heatmap = alt.Chart(heat).mark_rect().encode(
                x=alt.X("Month:T", title="Month"),
                y=alt.Y("Team:N", sort=teams_sel, title=None),
                color=alt.Color("Events:Q"),
                tooltip=["Team:N", "Month:T", "Events:Q"],
            )
            st.altair_chart(heatmap.properties(height=220), use_container_width=True)

elif page == "Diagnostics":
    st.subheader("Data preview")
    st.caption(f"Showing all {len(view_df)} rows")
    st.dataframe(view_df, use_container_width=True)

elif page == "Team::Reliability":
    st.subheader("Reliability (SLE)")
    st.caption("SLE is fixed at **85% reliability**. Define thresholds (days) per issue type, then track % delivered within SLE.")

    # --- Config UI ---
    default_sle = {
        "Story": 10,
        "Bug": 5,
        "Task": 8,
        "Spike": 12,
    }
    sle_cfg = dict(default_sle)
    sle_cfg.update(CFG.get("sle_days_by_type", {}) or {})

    st.markdown("### SLE thresholds (days)")
    sle_rows = []
    for it in ["Story", "Bug", "Task", "Spike"]:
        sle_rows.append({"IssueType": it, "SLE_days": int(sle_cfg.get(it, default_sle[it]))})
    sle_df = st.data_editor(pd.DataFrame(sle_rows), hide_index=True, use_container_width=True)

    c_save, c_hint = st.columns([1, 3])
    if c_save.button("Save SLE thresholds", type="primary"):
        new_cfg = dict(CFG)
        try:
            m = {}
            for _, r in sle_df.iterrows():
                m[str(r["IssueType"])]= int(r["SLE_days"]) if pd.notna(r["SLE_days"]) else None
            new_cfg["sle_days_by_type"] = {k: v for k, v in m.items() if v is not None}
            save_config(new_cfg)
            st.success("Saved to config.json")
            st.rerun()
        except Exception as e:
            st.error(f"Could not save SLE thresholds: {e}")

    c_hint.caption("These thresholds are saved locally in config.json and apply per team selection.")

    st.divider()

    # --- Calculations ---
    if view_df.empty or "End" not in view_df.columns or "CT" not in view_df.columns or "IssueType" not in view_df.columns:
        st.info("No completed item data with IssueType available.")
    else:
        d = view_df[["Key", "Summary", "IssueType", "CT", "End"]].copy()
        d["End"] = pd.to_datetime(d["End"], utc=True, errors="coerce")
        d = d.dropna(subset=["End", "CT", "IssueType"])

        if d.empty:
            st.info("No completed items to evaluate against SLE.")
        else:
            # last 30d window
            end_max = d["End"].max()
            start_30 = end_max - pd.Timedelta(days=30)
            d30 = d[(d["End"] >= start_30) & (d["End"] <= end_max)].copy()

            sle_map = CFG.get("sle_days_by_type", {}) or default_sle

            def _within(row):
                thr = sle_map.get(str(row["IssueType"]))
                if thr is None:
                    return np.nan
                return float(row["CT"]) <= float(thr)

            d30["within_sle"] = d30.apply(_within, axis=1)
            d30_eval = d30.dropna(subset=["within_sle"]).copy()

            # Overall reliability (weighted by item count across types with thresholds)
            overall_rel = None
            if not d30_eval.empty:
                overall_rel = float(d30_eval["within_sle"].mean())

            k1, k2, k3 = st.columns(3)
            k1.metric("SLE target", "85%")
            k2.metric("Reliability (last 30d)", "—" if overall_rel is None else f"{overall_rel*100:.0f}%")
            k3.metric("Items evaluated (last 30d)", f"{len(d30_eval)}")

            st.markdown("### By issue type (last 30d)")
            cols = st.columns(4)
            for i, it in enumerate(["Story", "Bug", "Task", "Spike"]):
                thr = sle_map.get(it)
                sub = d30[d30["IssueType"] == it].copy()
                sub["within_sle"] = sub.apply(_within, axis=1)
                sub = sub.dropna(subset=["within_sle"])
                rel = float(sub["within_sle"].mean()) if not sub.empty else None
                cols[i].metric(
                    f"{it} (≤ {thr}d)",
                    "—" if rel is None else f"{rel*100:.0f}%",
                )
                cols[i].caption(f"n={len(sub)}")

            st.divider()

            # Monthly reliability trend (overall)
            st.markdown("### Reliability trend")
            d["month"] = d["End"].dt.to_period("M").dt.to_timestamp("M")
            d["within_sle"] = d.apply(_within, axis=1)
            d_eval = d.dropna(subset=["within_sle"]).copy()

            if d_eval.empty:
                st.info("No items match the configured SLE types.")
            else:
                monthly = (
                    d_eval.groupby("month", as_index=False)
                    .agg(reliability=("within_sle", "mean"), count=("within_sle", "size"))
                    .sort_values("month")
                )

                chart = (
                    alt.Chart(monthly)
                    .mark_line(point=True)
                    .encode(
                        x=alt.X("month:T", title="Month"),
                        y=alt.Y("reliability:Q", title="Reliability", axis=alt.Axis(format="%"), scale=alt.Scale(domain=[0, 1])),
                        tooltip=[
                            alt.Tooltip("month:T", title="Month"),
                            alt.Tooltip("reliability:Q", title="Reliability", format=".0%"),
                            alt.Tooltip("count:Q", title="Items"),
                        ],
                    )
                )
                target = alt.Chart(pd.DataFrame({"y": [0.85]})).mark_rule(strokeDash=[6, 4], color="#22D3EE", opacity=0.7).encode(y="y:Q")
                st.altair_chart((chart + target).properties(height=320), use_container_width=True)

            st.divider()

            # Breaches (last 30d)
            st.markdown("### Breaches (last 30d)")
            if d30_eval.empty:
                st.info("No evaluated items in the last 30 days.")
            else:
                breaches = d30_eval[~d30_eval["within_sle"]].copy()
                if breaches.empty:
                    st.success("No breaches in the last 30 days.")
                else:
                    breaches["SLE_days"] = breaches["IssueType"].map(sle_map)
                    st.dataframe(
                        breaches[[c for c in ["Key", "Summary", "IssueType", "CT", "SLE_days", "End"] if c in breaches.columns]]
                        .sort_values("CT", ascending=False)
                        .reset_index(drop=True),
                        use_container_width=True,
                    )

elif page == "Team::Risks":
    st.subheader("Risks (Aging WIP)")
    st.caption("In-flight items with a Start date and no Done date. Flags items likely to breach SLE based on current age.")

    if view_df.empty:
        st.info("No data available.")
    else:
        # Parse dates
        d = view_df.copy()
        if "Start" in d.columns:
            d["Start"] = pd.to_datetime(d["Start"], utc=True, errors="coerce")
        else:
            d["Start"] = pd.NaT
        if "End" in d.columns:
            d["End"] = pd.to_datetime(d["End"], utc=True, errors="coerce")
        else:
            d["End"] = pd.NaT

        # WIP: started but not done
        wip = d[d["Start"].notna() & d["End"].isna()].copy()
        if wip.empty:
            st.success("No in-flight items found (with Start date and no Done date).")
        else:
            now = pd.Timestamp.now(tz="UTC")
            wip["Age_days"] = (now - wip["Start"]).dt.total_seconds() / 86400.0

            # SLE map (from config or defaults)
            default_sle = {"Story": 10, "Bug": 5, "Task": 8, "Spike": 12}
            sle_map = dict(default_sle)
            sle_map.update(CFG.get("sle_days_by_type", {}) or {})

            wip["SLE_days"] = wip.get("IssueType").astype(str).map(sle_map)
            wip["Risk"] = np.where(
                wip["SLE_days"].notna() & (wip["Age_days"] >= wip["SLE_days"]),
                "Breached",
                np.where(
                    wip["SLE_days"].notna() & (wip["Age_days"] >= 0.8 * wip["SLE_days"]),
                    "At risk",
                    "OK",
                ),
            )

            # KPIs
            k1, k2, k3, k4 = st.columns(4)
            k1.metric("WIP items", f"{len(wip)}")
            k2.metric("At risk", f"{int((wip['Risk'] == 'At risk').sum())}")
            k3.metric("Breached", f"{int((wip['Risk'] == 'Breached').sum())}")
            k4.metric("Oldest (days)", f"{float(wip['Age_days'].max()):.1f}")

            st.divider()

            # Filters
            f1, f2, f3 = st.columns([1, 1, 1.2])
            types = sorted([t for t in wip.get("IssueType", pd.Series(dtype=str)).dropna().astype(str).unique().tolist() if t])
            type_sel = f1.selectbox("Issue type", ["All"] + types, index=0)
            risk_sel = f2.selectbox("Risk", ["All", "OK", "At risk", "Breached"], index=0)
            only_risky = f3.checkbox("Only show At risk / Breached", value=False)

            show = wip.copy()
            if type_sel != "All" and "IssueType" in show.columns:
                show = show[show["IssueType"].astype(str) == type_sel]
            if risk_sel != "All":
                show = show[show["Risk"] == risk_sel]
            if only_risky:
                show = show[show["Risk"].isin(["At risk", "Breached"])]

            st.markdown("### In-flight items")
            cols = [c for c in ["Key", "Summary", "Team", "IssueType", "Start", "Age_days", "SLE_days", "Risk", "CT"] if c in show.columns]
            # Ensure CT isn't misleading for WIP; keep it last if present
            if "CT" in cols:
                cols = [c for c in cols if c != "CT"] + ["CT"]

            show = show.sort_values(["Risk", "Age_days"], ascending=[True, False])
            # Nicer formatting
            if "Age_days" in show.columns:
                show["Age_days"] = show["Age_days"].round(1)

            st.dataframe(show[cols].reset_index(drop=True), use_container_width=True)

            st.markdown("### Risk breakdown")
            risk_counts = show["Risk"].value_counts().reindex(["OK", "At risk", "Breached"]).fillna(0).astype(int).reset_index()
            risk_counts.columns = ["Risk", "Count"]
            bar = alt.Chart(risk_counts).mark_bar().encode(
                x=alt.X("Risk:N", sort=["OK", "At risk", "Breached"]),
                y=alt.Y("Count:Q"),
                color=alt.Color("Risk:N", scale=alt.Scale(domain=["OK", "At risk", "Breached"], range=["#34D399", "#FBBF24", "#F43F5E"]))
            )
            st.altair_chart(bar.properties(height=220), use_container_width=True)

elif page == "Team::Bottlenecks":
    st.subheader("Bottlenecks")
    st.caption("Identify where time is accumulating using your bucket definitions.")

    if view_df.empty or "CT" not in view_df.columns:
        st.info("No data available.")
    else:
        # Buckets are any numeric columns besides CT plus known fields
        ignore = {"CT", "Key", "Summary", "Team", "IssueType", "Sprint", "Start", "End", "_bucketer"}
        bucket_cols = [c for c in view_df.columns if c not in ignore and pd.api.types.is_numeric_dtype(view_df[c])]

        if not bucket_cols:
            st.info("No bucket duration columns found. Check your Rules (Status Buckets).")
        else:
            # Configure which buckets are considered 'waiting'
            default_waiting = [c for c in bucket_cols if c.lower() in ("blocked", "review")]
            waiting_default = CFG.get("waiting_buckets", default_waiting)

            st.markdown("### Waiting vs Working")
            waiting_sel = st.multiselect(
                "Buckets treated as waiting",
                options=bucket_cols,
                default=[b for b in waiting_default if b in bucket_cols],
                help="Waiting = non-value-add delay (e.g., Blocked, Review). Working = remaining buckets.",
            )

            work_cols = [c for c in bucket_cols if c not in waiting_sel]

            completed = view_df.dropna(subset=["End", "CT"]).copy() if "End" in view_df.columns else view_df.copy()
            completed = completed[completed["CT"].notna()] if "CT" in completed.columns else completed

            if completed.empty:
                st.info("No completed items available for bottleneck analysis.")
            else:
                # Shares across completed items (sum durations)
                wait_sum = float(completed[waiting_sel].sum().sum()) if waiting_sel else 0.0
                work_sum = float(completed[work_cols].sum().sum()) if work_cols else 0.0
                total = wait_sum + work_sum

                c1, c2, c3, c4 = st.columns(4)
                c1.metric("Completed items", f"{len(completed)}")
                c2.metric("Waiting share", "—" if total == 0 else f"{(wait_sum/total)*100:.0f}%")
                c3.metric("Working share", "—" if total == 0 else f"{(work_sum/total)*100:.0f}%")
                c4.metric("Avg CT", f"{completed['CT'].mean():.1f} d" if completed["CT"].notna().any() else "—")

                st.divider()

                st.markdown("### Where time is going (all completed items)")
                # Bucket ranking by total time
                totals = completed[bucket_cols].sum().sort_values(ascending=False)
                df_totals = totals.reset_index()
                df_totals.columns = ["Bucket", "TotalDays"]

                chart = alt.Chart(df_totals).mark_bar().encode(
                    x=alt.X("TotalDays:Q", title="Total days"),
                    y=alt.Y("Bucket:N", sort="-x"),
                    tooltip=[alt.Tooltip("Bucket:N"), alt.Tooltip("TotalDays:Q", format=".1f")],
                    color=alt.Color("Bucket:N", legend=None, scale=alt.Scale(range=["#22D3EE", "#A78BFA", "#34D399", "#FBBF24", "#F43F5E"]))
                )
                st.altair_chart(chart.properties(height=280), use_container_width=True)

                # Median per bucket per item (helps identify consistent bottlenecks)
                st.markdown("### Typical time per bucket (median days per item)")
                meds = completed[bucket_cols].median().sort_values(ascending=False)
                df_meds = meds.reset_index()
                df_meds.columns = ["Bucket", "MedianDays"]
                chart2 = alt.Chart(df_meds).mark_bar().encode(
                    x=alt.X("MedianDays:Q", title="Median days per item"),
                    y=alt.Y("Bucket:N", sort="-x"),
                    tooltip=[alt.Tooltip("Bucket:N"), alt.Tooltip("MedianDays:Q", format=".2f")],
                    color=alt.value("#A78BFA")
                )
                st.altair_chart(chart2.properties(height=280), use_container_width=True)

                st.divider()

                # --- Insights ---
                st.markdown("### Insights")
                try:
                    total_by_bucket = completed[bucket_cols].sum().sort_values(ascending=False)
                    total_time = float(total_by_bucket.sum())
                    top_bucket = str(total_by_bucket.index[0]) if len(total_by_bucket) else None
                    top_bucket_share = (float(total_by_bucket.iloc[0]) / total_time) if total_time else None

                    # Waiting bucket share
                    wait_share = (wait_sum / total) if total else None

                    insight_lines = []
                    if top_bucket and top_bucket_share is not None:
                        insight_lines.append(f"- Biggest time contributor: **{top_bucket}** ({top_bucket_share*100:.0f}% of total bucket time).")
                    if wait_share is not None:
                        insight_lines.append(f"- Waiting share (selected buckets): **{wait_share*100:.0f}%**.")

                    # Trend delta vs last 3 months (if possible)
                    if "End" in completed.columns:
                        tmpi = completed.copy()
                        tmpi["End"] = pd.to_datetime(tmpi["End"], utc=True, errors="coerce")
                        tmpi = tmpi.dropna(subset=["End"])
                        if not tmpi.empty and waiting_sel:
                            tmpi["month"] = tmpi["End"].dt.to_period("M").dt.to_timestamp("M")
                            tmpi["waiting"] = tmpi[waiting_sel].sum(axis=1)
                            tmpi["working"] = tmpi[work_cols].sum(axis=1) if work_cols else 0.0
                            tmpi["total"] = tmpi["waiting"] + tmpi["working"]
                            tmpi = tmpi[tmpi["total"] > 0]
                            if not tmpi.empty:
                                m = tmpi.groupby("month").apply(lambda g: float(g["waiting"].sum())/float(g["total"].sum()) if float(g["total"].sum()) else np.nan)
                                m = m.dropna().sort_index()
                                if len(m) >= 2:
                                    delta = float(m.iloc[-1] - m.iloc[0])
                                    insight_lines.append(f"- Waiting share change (first→last month in view): **{delta*100:+.0f}%**.")

                    # Top breached items by selected waiting buckets
                    if waiting_sel:
                        tmpw = completed.copy()
                        tmpw["waiting"] = tmpw[waiting_sel].sum(axis=1)
                        top_wait = tmpw.sort_values("waiting", ascending=False).head(10)
                        if not top_wait.empty:
                            tw = float(top_wait["waiting"].median())
                            insight_lines.append(f"- Top 10 items by waiting time have median waiting of **{tw:.1f} days**.")

                    if insight_lines:
                        st.markdown("\n".join(insight_lines))
                    else:
                        st.info("Not enough data to generate insights yet.")
                except Exception:
                    st.info("Not enough data to generate insights yet.")

                st.divider()

                st.markdown("### Trend: waiting share by month")
                if "End" in completed.columns:
                    tmp = completed.copy()
                    tmp["End"] = pd.to_datetime(tmp["End"], utc=True, errors="coerce")
                    tmp = tmp.dropna(subset=["End"])
                    if tmp.empty:
                        st.info("No End dates to build a trend.")
                    else:
                        tmp["month"] = tmp["End"].dt.to_period("M").dt.to_timestamp("M")
                        if waiting_sel:
                            tmp["waiting"] = tmp[waiting_sel].sum(axis=1)
                        else:
                            tmp["waiting"] = 0.0
                        tmp["working"] = tmp[work_cols].sum(axis=1) if work_cols else 0.0
                        tmp["total"] = tmp["waiting"] + tmp["working"]
                        tmp = tmp[tmp["total"] > 0]

                        monthly = tmp.groupby("month", as_index=False).agg(
                            waiting_share=("waiting", lambda x: float(x.sum()) / float(tmp.loc[x.index, "total"].sum()) if float(tmp.loc[x.index, "total"].sum()) else np.nan),
                            count=("total", "size"),
                        )

                        trend = alt.Chart(monthly).mark_line(point=True).encode(
                            x=alt.X("month:T", title="Month"),
                            y=alt.Y("waiting_share:Q", title="Waiting share", axis=alt.Axis(format="%"), scale=alt.Scale(domain=[0, 1])),
                            tooltip=["month:T", alt.Tooltip("waiting_share:Q", format=".0%"), "count:Q"],
                        )
                        st.altair_chart(trend.properties(height=320), use_container_width=True)
                else:
                    st.info("No End dates available to build a monthly trend.")

                # Export + save settings
                cexp1, cexp2 = st.columns([1, 1])

                # CSV export of bucket summary
                try:
                    export_totals = completed[["Key", "Summary", "Team", "IssueType", "Start", "End", "CT"] + bucket_cols].copy()
                except Exception:
                    export_totals = completed.copy()

                csv_bytes = export_totals.to_csv(index=False).encode("utf-8")
                cexp1.download_button(
                    "Export completed items (CSV)",
                    data=csv_bytes,
                    file_name="ctapp_bottlenecks_completed_items.csv",
                    mime="text/csv",
                    use_container_width=True,
                )

                if cexp2.button("Save waiting bucket selection", use_container_width=True):
                    new_cfg = dict(CFG)
                    new_cfg["waiting_buckets"] = waiting_sel
                    save_config(new_cfg)
                    st.success("Saved to config.json")
